### ISSUE TITLE
接口申请：最新文章

### ISSUE THREAD

**Issue by musicoooool** [lanny540/cbpcweb#10]
**命名：**  api/latest
**条件：**
1. num，返回文章的数量
2. cid，栏目数组，如，cid=1,2,3

注意：和前面提供的api/post?num=5&cid=1,2,3接口不同的是，最新文章接口返回的是混合指定栏目的文章，sql句式如：select * from posts where category_id in (1,2,3) order by create_at desc limit 5

**返回：**
返回json格式如下
```
[
	{
		id: 48,
		title: "Enim cumque ut ipsum accusamus aut non quo.",
		clicks: 383270233,
		imageurl: "/static/upload/default.jpg",
		category_name: "栏目名称",
		published_at: "2017-08-21"
	},
	...
]
```

**Comment by lanny540** [comment]
`$api->get('latest', 'PostController@latest');`

- @url /api/latest?num=5&cid=1,2,3
- num，返回文章的数量
 - cid，栏目数组，如，cid=1,2,3

**Comment by lanny540** [comment]
接口已测试，关闭
