### ISSUE TITLE
接口申请：专栏列表

### ISSUE THREAD

**Issue by musicoooool** [lanny540/cbpcweb#11]
**命名：** api/topic
**参数条件：**
1. num：返回专栏的数量，可以为空，为空代表所有公开（过期的，或人为设置为失效的会被隐藏）的专题
2. per：每页数量，默认值=10
3. p：第几页，默认值=1
**举例：**
> **api/topic?num=4**
> 请求得到4个最新的、有效的专栏列表
>
> **api/topic?per=10&p=2
> 返回所有专栏中按创建时间倒排，有效的专栏，排序序号在11至20之间的10个专栏的列表

**返回：**
```
[
	{
		id: 1,
		name: "专栏名称",
		description: "专栏简介",
		imageurl: "栏目缩略图",
		create_at: "创建时间"
	},
	......
]
```

**Comment by lanny540** [comment]
我把 SQL 语句也大概写在下面，你们也看下有没有问题哈。！！
`SELECT * FROM columns WHERE is_show = 1 AND period > "当前时间" ORDER BY created_at`

- url:  `api/topic?num=4&per=10&page=2`
- num：返回专栏的数量，可以为空，为空代表所有公开（过期的，或人为设置为失效的会被隐藏）的专题
- per: 默认值=10
- page: 页数

**Comment by lanny540** [comment]
建议不要考虑分页，因为专栏本来就少。
@musicoooool

**Comment by lanny540** [comment]
@musicoooool 
新增了一个  专栏文章接口
- url:  `api/topic/2?per=8&page=1
- per:  每页显示文章数，默认10
- page: 页数
