### ISSUE TITLE
接口申请：媒体库

### ISSUE THREAD

**Issue by realeve** [lanny540/cbpcweb#13]
# 表单  gallery
`CREATE TABLE gallery (
  id int(11) NOT NULL AUTO_INCREMENT,
  uid int(11) DEFAULT NULL,
  file_name varchar(255) DEFAULT NULL,
  file_type varchar(255) DEFAULT NULL,
  file_size double DEFAULT NULL,
  file_url varchar(255) DEFAULT NULL,
  width double DEFAULT NULL,
  height double DEFAULT NULL,
  rec_time datetime DEFAULT NULL,
  PRIMARY KEY (id)
)  #ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;`

列表读取接口1：

> select * from gallery where uid=? order by id desc limit 20

列表读取接口2：

> select * from gallery where uid=? and id< ? order by id desc limit 20

 写入数据接口，内容如下：
  uid:0
  file_name:6.jpg
  file_type:images/webp
  file_size:97.35
  width:1920
  height:1080
  file_url:/assets/2017/08/webp/1503580264_919402Q10v3aJ77i1A5ItleU6u4q82mLWP2O5n.webp
  rec_time:2017-08-24 21:11:05

**Comment by lanny540** [comment]
```php
      $table->bigIncrements('id');
      $table->integer('user_id')->unsigned()->index()->comment('上传用户ID');
      $table->foreign('user_id')->references('id')->on('users')->onUpdate('cascade')->onDelete('cascade');
      $table->string('file_name ')->comment('上传文件名称');
      $table->string('file_type')->comment('文件类型');
      $table->string('file_url')->comment('文件在CDN的路径');
      $table->double('file_size ')->comment('文件大小');
      $table->smallInteger('width')->comment('图片宽');
      $table->smallInteger('height')->comment('图片高');
      $table->timestamps();
```

**Comment by lanny540** [comment]
@realeve  把  长、宽 的字段类型改成了 smallinteger
