### ISSUE TITLE
增加查询指定的多个栏目最新 X条 文章的api接口实现

### ISSUE THREAD

**Issue by musicoooool** [lanny540/cbpcweb#2]
现在PostController.postslist接口返回的是所有栏目X条文章，需要进一步支持查询指定的多个栏目最新X条文章的实现。
注意：
1. 如果栏目中有置顶显示的文章，必须包含在返回结果中；
2. 优化sql，减少查询次数，建议使用sql union查询方法，如：select * from A union (select * from B) union (...)
3. 明确指定的多个栏目的http request参数名称和格式

**Comment by lanny540** [comment]
可选参数： 
- `cids`  栏目字符串，比如  `cids=1,2,3,5`
- `postsnumber` 每个栏目查询的文章数

最终效果类似 
`http://xxxxxxxxx?cids=1,2,3,6,9&postsnumber=5`

问题2 后续解决，问题1 排序的优先级是  is_top,published_at
