### ISSUE TITLE
需要增加对CROS的支持

### ISSUE THREAD

**Issue by musicoooool** [lanny540/cbpcweb#5]
建议在index.php中增加：
header('Access-Control-Allow-Origin: [trusted site]');
header('Access-Control-Allow-Methods: GET, POST, PATCH, PUT, DELETE, OPTIONS');
header('Access-Control-Allow-Headers: Origin, Content-Type, X-Auth-Token');
header('Access-Control-Allow-Credentials: true');

**Comment by lanny540** [comment]
已添加!
