### ISSUE TITLE
审核流程

### ISSUE THREAD

**Issue by musicoooool** [lanny540/cbpcweb#8]
**审核流程**
1. 变更level和status
> api地址：api/approve
> 请求条件:{id:xxxxx,level:1,status:1}
> 返回：{result:"success"/"error",code:"(validate error code)"}

**Comment by lanny540** [comment]
接口  PUT 方式，加入了请求验证；
```php
'id' => 'required|int',
'level' => 'required|int',
'status' => 'required|int',
```
